### PR TITLE
trying to add other ecr cred

### PR DESCRIPTION
**Pull request by 2byrds**
@aydarng i'll put this in draft, i've run out of time today. Maybe you can take a look. I'm trying to create an 'other ecr' that isn't an EBA Data Submitter to test the bug you reported.

### CODE REVIEW

**Comment by 2byrds** [comment]
@aydarng I have added the ability to process each credential, and then modify the expected response if 'isEbaDataSubmitter'. There are now several failures but i didn't have time to go through them to see if it is a verifier or test-change issue. i'll look into it more but wanted to share.

**Comment by aydarng** [comment]
> @aydarng I have added the ability to process each credential, and then modify the expected response if 'isEbaDataSubmitter'. There are now several failures but i didn't have time to go through them to see if it is a verifier or test-change issue. i'll look into it more but wanted to share.

@2byrds Looks good!

**Comment by 2byrds** [comment]
@aydarng I have added the ability to submit all creds that the user/aid has. And to expect on the eba data submitter cred logins/checklogins to succeed.

**Comment by 2byrds** [comment]
also @aydarng to help the single sig and multisig use cases to converge the api test, i pulled the /login and /checklogin portions of those tests into a share method. We might be able to continue to do that to make the testing more dynamic depending on config/workflow.

**Pull request merged**
